config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  #[:show, :index, :new, :create, :edit, :update, :destroy]
  resources :articles do
    resources :comments
  end
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  has_many :comments

  validates :title, presence: true#, length: { minimum:4, maximum:100 }
  validates :description, presence: true#, length: { minimum:10, maximum:300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: { minimum:3, maximum:25 }
  validates_uniqueness_of :name

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum:3, maximum:25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in"
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_appropriate_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)
  end

  def show
    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_appropriate_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You must be creator of that article to handle that operation"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
      if @category.update(category_params)
        flash[:notice] = "Category was successfully updated"
        redirect_to @category
      else
        render 'edit'
      end
  end
  

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  before_action :set_comment, only: [:destroy]
  before_action :require_appropriate_user, only: [:destroy]

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.user = current_user

    @comment.save

    redirect_to article_path(@comment.article)
  end

  def destroy
    @comment.destroy

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end

  def set_comment
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
  end

  def require_appropriate_user
    if current_user.id != @comment.user_id && !current_user.admin?
      flash[:alert] = "You must be creator of that comment to handle that operation"
      redirect_to @article
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to articles_path
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out successfully"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_appropriate_user, only: [:edit, :update, :destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 4)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 4)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the Alpa Blog #{@user.username}, you have successfully signed up!"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user = current_user
    flash[:notice] = "#{@user.username} and articles successfully deleted."
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_appropriate_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "It must be your profile to handle that operation"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto shadow d-block")
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_articles.html.erb
<div class="container d-flex align-items-center flex-column mt-2">
  <% @articles.each do |a| %>
    <div class="card text-center shadow mb-5 bg-body rounded" style="width: 45em;">
      <div class="card-header fst-italic">
        by <%= link_to a.user.username, user_path(a.user) %></br>
        <% if a.categories.any? %>
          <%= render a.categories %>
        <% end %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><%= link_to a.title, article_path(a), class:"text-success text-decoration-none" %></h5>
        <p class="card-text"><%= truncate(a.description, length: 100) %></p>
        <% if logged_in? && (a.user == current_user || current_user.admin?) %>
          <%= link_to "Show", article_path(a), class:"btn btn-outline-primary" %>
          <%= link_to "Edit", edit_article_path(a), class:"btn btn-outline-success" %>
          <%= link_to "Delete", article_path(a), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"btn btn-outline-danger" %>
        <% end %>
      </div>
      <div class="card-footer text-muted">
        <small>
          Created <%= time_ago_in_words(a.created_at) %> ago,
          edited <%= time_ago_in_words(a.updated_at) %> ago
        </small>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_with(model: @article, local: true) do |f| %>
  <div class="container border rounded p-4 bg-light shadow" style="width: 45em;">
    <div class="mb-4">
      <%= f.label :title, class:"form-label" %></br>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="mb-4">
      <%= f.label :description, class:"form-label" %></br>
      <%= f.text_area :description, class:"form-control" %>
    </div>
    <div class="mb-4">
      <%= f.label :category, class:"form-label" %></br>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
        <%= b.check_box class:"btn-check" %>
        <%= b.label class:"btn btn-outline-secondary" %>
      <% end %>
    </div></br>

    <%= f.submit class:"btn btn-success" %>
    <%= link_to "Cancel", articles_path, class:"btn btn-danger" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Articles</h1>

<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles' %>

<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4 mb-4">New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1 class="text-center mt-4 mb-4">Article</h1>

<div class="container d-flex align-items-center flex-column">
  <div class="card text-center shadow mb-5 bg-body rounded" style="width: 45em;">
    <div class="card-header fst-italic">
      by <%= @article.user.username %></br>
      <% if @article.categories.any? %>
        <%= render @article.categories %>
      <% end %>
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @article.title %></h5>
      <div class="card-text"><%= simple_format(@article.description) %></div>
      <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
        <%= link_to "Edit", edit_article_path(@article), class:"btn btn-outline-success" %>
        <%= link_to "Delete", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"btn btn-outline-danger" %>
      <% end %>
    </div>
    <div class="card-footer text-muted">
      <small>
        Created <%= time_ago_in_words(@article.created_at) %> ago,
        edited <%= time_ago_in_words(@article.updated_at) %> ago
      </small>
    </div>
  </div>
  <div class="card shadow" style="width: 45em;">
    <h5 class="card-header text-center">Comments
    <span class="fw-light"><%= @article.comments.count %></span>
    </h5>
    <%= render 'comments/form' %>
    <ul class="list-group text-start">
      <%= render 'comments/comments' %>
    </ul>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"badge rounded-pill text-bg-primary text-decoration-none mt-2 mx-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>

<%= form_with(model: @category, local: true) do |u| %>
  <div class="container border rounded p-4 bg-light shadow" style="width: 45em;">
    <div class="mb-3">
      <%= u.label :name, class:"form-label" %></br>
      <%= u.text_field :name, class:"form-control" %>
    </div>
    <%= u.submit class:"btn btn-success" %>
    <%= link_to "Cancel", articles_path, class:"btn btn-danger" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 mb-4">Categories</h1>

<div class="apple_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<div class="container d-flex align-items-center flex-column mt-2">
  <% @categories.each do |c| %>
    <div class="card text-center shadow mb-5 bg-body rounded" style="width: 45em;">
      <div class="card-body">
        <h5 class="card-title"><%= link_to c.name, category_path(c), class:"text-success text-decoration-none" %></h5>
        <%= pluralize(c.articles.count, "article") %>
      </div>
      <div class="card-footer text-muted">
        <small>
          Created <%= time_ago_in_words(c.created_at) %> ago,
          edited <%= time_ago_in_words(c.updated_at) %> ago
        </small>
      </div>
    </div>
  <% end %>
</div>

<div class="apple_pagination">
  <%= will_paginate @cateogries, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4 mb-4">Create category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="text-center mt-4 mb-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class:"btn btn-outline-success" %>
  </div>
<% end %>

<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/articles' %>

<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/comments/_comments.html.erb
<% @article.comments.reverse_each do |c| %>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <div>
      <div>
        <strong><%= link_to c.user.username, user_path(c.user) %></strong> 
        <span class="fw-light"><%= time_ago_in_words(c.created_at) %> ago</span>
      </div>
      <div><%= c.text %></div>
    </div>
    <% if current_user.id == c.user_id %>
      <%= link_to '', article_comment_path(c.article, c), data: { turbo_method: :delete }, class:"btn-close"  %>
    <% end %>
  </li>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [ @article, @comment ] do |f| %>
  <div class="input-group">
    <%= f.text_field :text, class:"form-control" %>
    <%= f.submit class:"btn btn-primary input-group-text" %>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="d-flex justify-content-center mt-4">
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert" style="width: 45em;">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" id="logo" href="/">AlphaBlog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class:"nav-link" %>
        </li>
        <% if logged_in? && current_user.admin? %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View categories", categories_path, class:"dropdown-item" %></li>
              <li><%= link_to "New category", new_category_path, class:"dropdown-item" %></li>
            </ul>
          </li>
        <% elsif %>
          <li class="nav-item">
            <%= link_to "Categories", categories_path, class:"nav-link" %>
          </li>
        <% end %>
        <% if logged_in? %>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Acrticles
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Articles", articles_path, class:"dropdown-item" %></li>
              <li><%= link_to "New article", new_article_path, class:"dropdown-item" %></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profile
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View profile", user_path(current_user), class:"dropdown-item" %></li>
              <li><%= link_to "Edit profile", edit_user_path(current_user), class:"dropdown-item" %></li>
              <li><%= link_to "Log out", logout_path, class:"dropdown-item text-danger", data: { turbo_method: :delete } %></li>
              <li><%= button_to "Delete account", user_path(current_user), class:"dropdown-item text-danger", method: :delete, form: { data: { turbo_confirm: "Are you sure?" } } %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Articles", articles_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log in", login_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%#= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class='container' id="home-container">
  <div class="bg-light p-5 rounded-lg m-3">
    <h1 class="display-4">Welcome on Alpha Blog</h1>
    <p class="lead">You can post here your articles, comment and read another's.</p>
    <hr class="my-4">
    <p>Just one more step to use that blog - you need to create account.</p>
    <%= link_to 'Sign up', signup_path, class:"btn btn-primary btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="d-flex justify-content-center">
    <div class="alert alert-danger alert-dismissible fade show" role="alert" style="width: 45em;">
      <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_with(model: @user, local: true) do |u| %>
  <div class="container border rounded p-4 bg-light shadow" style="width: 45em;">
    <div class="mb-3">
      <%= u.label :username, class:"form-label" %></br>
      <%= u.text_field :username, class:"form-control" %>
    </div>
    <div class="mb-4">
      <%= u.label :email, class:"form-label" %></br>
      <%= u.email_field :email, class:"form-control" %>
    </div>
    <div class="mb-4">
      <%= u.label :password, class:"form-label" %></br>
      <%= u.password_field :password, class:"form-control" %>
    </div>
    <%= u.submit(@user.new_record? ? "Sign up" : "Update", class:"btn btn-success") %>
    <%= link_to "Cancel", articles_path, class:"btn btn-danger" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="text-center mt-4 mb-4">Edit profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4 mb-4">Bloggers</h1>

<div class="apple_pagination">
  <%= will_paginate @users, :container => false %>
</div>


<div class="container d-flex align-items-center flex-column mt-2">
  <% @users.each do |u| %>
    <div class="card text-center shadow mb-5 bg-body rounded" style="width: 45em;">
      <div class="card-header fst-italic">
        <%= u.username %>
      </div>
      <div class="card-body">
        <%= gravatar_for u, size: 200 %>
        <div class="mt-2 mb-2"><%= pluralize(u.articles.count, "article") %></div>
        <%= link_to "View profile", user_path(u), class:"btn btn-outline-primary" %>
        <% if logged_in? %>
          <% if u == current_user %>
            <%= link_to "Edit profile", edit_user_path(u), class:"btn btn-outline-success" %>
          <% end %>
          <% if current_user.admin? %>
            <%= link_to "Delete user", user_path(u), class:"btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          <% end %>
        <%end %>
      </div>
      <div class="card-footer text-muted">
        <small>
          Joined <%= time_ago_in_words(u.created_at) %> ago
        </small>
      </div>
    </div>
  <% end %>
</div>

<div class="apple_pagination">
  <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4 mb-4">Sing up</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4 mb-4"><%= @user.username %> profile</h1>

<%= gravatar_for @user, size: 200 %>

<% if logged_in? && @user == current_user %>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile", edit_user_path(@user), class:"btn btn-outline-success" %>
  </div>
<% end %>

<% if @user.articles.length > 0 %>
  <h3 class="text-center mt-4 mb-4">Articles</h3>
<% else %>
  <h3 class="text-center mt-4">No articles</h3>
<% end %>

<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/articles' %>

<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>